### ISSUE TITLE
Rename Date Column title on FairCoin block explorer

### ISSUE THREAD

**Issue by MichalisKas** [faircoin/faircoin2#17]
Need to change the title on Date Column from (M - D - Y) to (Y - M - D) in order to correspond to the date shown. Example https://chain.fair.to/address?address=fMfx6gGzWjohAWvvcyGPhrTwzWtsZoLyQo

**Comment by thokon00** [comment]
Thanks for reporting, but this is not a Core wallet issue. Please report to this project: https://github.com/faircoin/faircoin2-cce-4.0
