### ISSUE TITLE
Worry about encrypted  wallet.dat

### ISSUE THREAD

**Issue by Al-Demon** [faircoin/faircoin2#22]
Hello, I'm testing in the encrypted mode in the portfolio of faircoin for linux and do a "cat command" in the wallet.dat and I can see my faircoin address and the binary code that is similar to a wallet.dat no encryption

I don't know if this is correct or is not working the way encryption... If there is someone you can explain to me something I would be very grateful.

Thanks for this project

**Comment by capiscuas** [comment]
I am also very worry about this, I can replicate @Al-Demon 's issue.

**Comment by thokon00** [comment]
The wallet.dat file is not encrypted as a whole but the private keys only.

**Comment by capiscuas** [comment]
Thanks for the quick answer!
