### ISSUE TITLE
couldn't install on ubuntu 16.04

### ISSUE THREAD

**Issue by hpk42** [faircoin/faircoin2#5]
While executing `autogen.sh` this happened:

  configure.ac:20: installing 'build-aux/compile'
  configure.ac:5: installing 'build-aux/config.guess'
  configure.ac:5: installing 'build-aux/config.sub'
  configure.ac:9: installing 'build-aux/install-sh'
  configure.ac:9: installing 'build-aux/missing'
  Makefile.am:3: error: Libtool library used but 'LIBTOOL' is undefined
  Makefile.am:3:   The usual way to define 'LIBTOOL' is to add 'LT_INIT'
  Makefile.am:3:   to 'configure.ac' and run 'aclocal' and 'autoconf' again.
  Makefile.am:3:   If 'LT_INIT' is in 'configure.ac', make sure
  Makefile.am:3:   its definition is in aclocal's search path.
  Makefile.am: installing 'build-aux/depcomp'
  parallel-tests: installing 'build-aux/test-driver'
  autoreconf: automake failed with exit status: 1

This is an ubuntu 16.04 system.

**Comment by thokon00** [comment]
Are you sure all the required dependencies are installed? e.g.
`sudo apt-get install -y build-essential libtool autotools-dev autoconf pkg-config libssl-dev libboost-all-dev git libdb5.3-dev libdb5.3++-dev libqt4-core libqt4-gui libqt4-dev libqrencode-dev libprotobuf-dev protobuf-compiler libevent-dev`

**Comment by hpk42** [comment]
thanks, works now.  Got confused by `docs/build-unix.md` where i just read "To Build" and didn't see the apt-get commands further down.  now getting through configure at least ...
