### ISSUE TITLE
Have you experiences with OpenWRT?

### ISSUE THREAD

**Issue by Kuurusch** [faircoin/faircoin2#9]
Hallo, have you ever installed faircoin on a OpenWRT-System? My idea was to install it on the EnigmaBoxes (https://enigmabox.net/), because they run all by default 24/7.

I think that would support faircoin a lot!
Thanks for response!

**Comment by thokon00** [comment]
Do they offer enough resources, in terms of RAM and CPU power? What are the specs?

**Comment by Kuurusch** [comment]
I think yes, the boards are the apu-boards, the next generation of the famos alix-boards. And in near feature there will be a next geberation with AES-expand

**Comment by thokon00** [comment]
Closing this as it's not really a wallet issue. For further discussion use the FairCoin discussion group currently located on Telegram.
